host: 127.0.0.1
port: 3000
iceServerUrl: stun:stun.l.google.com:19302
# ----- WebSocket address setting -----
# pathForServer: server
# pathForClient: client
# ----- HTTPS setting -----
# https: true
# httpsKey: /path/to/private-key.key
# httpsCert: /path/to/certificate.crt